### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by sho-kasama** [sho-kasama/Todo-rails#38]
# Todo list

## 優先度高め

- [ ] taskのindexを全改造する。boostrapだと管理できない。Trello的な感じにしたい。

- [ ] usersコントローラーを作成して、プロフィールを編集できるようにする。その時のedit画面はTRUNKのコードを参考にする

- [ ] sign_up画面を作成する

- [ ] root toで飛ぶリンク先のページをtaskのindex画面にする？(ここ考える)

- [ ] ヘッダーをユーザーがログインしてないときは、sign_up画面に、ユーザーがログインしてる時は投稿画面に移動させるようにする

<img width="500" alt="スクリーンショット 2019-06-04 16 52 39" src="https://user-images.githubusercontent.com/40907757/58861435-513d8900-86e9-11e9-8ed1-a727c18dc2ef.png">

## 優先度 中

- [ ] FBログインができるようにする。

- [ ]
